### ISSUE TITLE
ImageComparisonFailure error during tests

### ISSUE THREAD

**Issue by ghisvail** [bayespy/bayespy#106]
I am getting the following error thrown during the tests:
```
======================================================================
FAIL: bayespy.tests.test_plot.test_contour_plot.test(1, '/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.6/build/result_images/test_plot/contour.png', '/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.6/build/result_images/test_plot/contour-expected.png')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/decorators.py", line 58, in failer
    result = f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/decorators.py", line 249, in do_test
    self._tol, in_decorator=True)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/compare.py", line 345, in compare_images
    rms = calculate_rms(expectedImage, actualImage)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/compare.py", line 256, in calculate_rms
    "actual size {1}".format(expectedImage.shape, actualImage.shape))
matplotlib.testing.exceptions.ImageComparisonFailure: image sizes do not match expected size: (480, 640, 3) actual size (600, 800, 3)
```

Sounds like file `bayespy/tests/baseline_images/test_plot/contour.png` has got a different size than the test is expecting.

**Comment by jluttine** [comment]
I made a new release 0.5.11. It skips this failing image comparison test. I'll deprecate all image comparison tests at some point and replace with something more robust. Does the new release work for you now?
