### ISSUE TITLE
nosetest warning

### ISSUE THREAD

**Issue by weiliu620** [bayespy/bayespy#19]
I've 'pip3 install' bayespy in my virtualenv, but saw a warning when I run nosetest: 

---------- begin log ---------------
(myvenv) Weis-MacBook-Air:~ weiliu$ pip freeze
bayespy==0.3.5
Cython==0.22.1
h5py==2.5.0
matplotlib==1.4.3
nose==1.3.7
numpy==1.9.2
pyparsing==2.0.3
python-dateutil==2.4.2
pytz==2015.4
scipy==0.15.1
six==1.9.0
(myvenv) Weis-MacBook-Air:~ weiliu$ nosetests bayespy
................................................................................................E..................
======================================================================
ERROR: Failure: RuntimeWarning (numpy.ufunc size changed, may indicate binary incompatibility)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/weiliu/myvenv/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/weiliu/myvenv/lib/python3.4/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/weiliu/myvenv/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/weiliu/myvenv/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/weiliu/myvenv/lib/python3.4/site-packages/bayespy/utils/covfunc/tests/test_distance.py", line 16, in <module>
    import scipy.spatial.distance as dist
  File "/Users/weiliu/myvenv/lib/python3.4/site-packages/scipy/spatial/__init__.py", line 90, in <module>
    from .ckdtree import *
  File "__init__.pxd", line 861, in init scipy.spatial.ckdtree (scipy/spatial/ckdtree.c:21116)
RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility

----------------------------------------------------------------------
Ran 115 tests in 14.507s

FAILED (errors=1)
======= end of log ===============

Any insights about this issue? Seems a upstream issue (bumpy binary compatible), though. 

Thanks. And, this package is great work!

**Comment by weiliu620** [comment]
Well I don't think it's a issue since I'm going through the user tutorial and don't see any problems. May be closed.

**Comment by jluttine** [comment]
As far as I can tell, it looks like an upstream issue, or a package installation issue. Maybe your SciPy has been compiled against a different version of NumPy than you're using in the virtual environment? If you get further insight about this and feel that it's an issue in BayesPy, please re-open this issue.
