### ISSUE TITLE
GaussianWishart 

### ISSUE THREAD

**Issue by raphaelcampos** [bayespy/bayespy#80]
I modeled a multivariate Gaussian approximation as follows:

```python
N, D = L.shape

Lambda = nodes.Wishart(D, np.identity(D))
mu = nodes.Gaussian(np.zeros(D), np.identity(D))
x = nodes.Gaussian(mu, Lambda, plates=(N,))
x.observe(L)

Q = VB(x, mu, Lambda)
Q.update(repeat=2000, tol=0, verbose=False)
```

It worked fine, however, I would like to improve the quality of the approximation by using GaussianWishart in a single node. I am facing some troubles using the distribution:

I tried to use the distribution this way:

```python
N, D = L.shape
mu = nodes.Gaussian(np.zeros(D), np.identity(D))
Lambda = nodes.Wishart(D, np.identity(D))
nodes.GaussianWishart(mu, 1, D, Lambda)
```
But I got the following error : 
```
File "/usr/local/lib/python3.4/dist-packages/bayespy/inference/vmp/nodes/gaussian.py", line 2041, in _constructor
    moments = GaussianWishartMoments(shape)
NameError: name 'shape' is not defined
```
I modified the code to this : 
```python
def _constructor(cls, mu, alpha, n, V, **kwargs):
        r"""
        Constructs distribution and moments objects.

        This method is called if useconstructor decorator is used for __init__.

        `mu` is the mean/location vector
        `alpha` is the scale
        `n` is the degrees of freedom
        `V` is the scale matrix
        """

        moments = GaussianWishartMoments(shape)

        # Convert parent nodes
        mu_alpha = WrapToGaussianGamma(mu, alpha)
        D = mu_alpha.dims[0][0]

        n = cls._ensure_moments(n, WishartPriorMoments)
        V = cls._ensure_moments(V, WishartMoments)
        
        shape = mu_Lambda.dims[0]

        moments = GaussianWishartMoments(shape)
        parent_moments = (
            mu_alpha._moments,
            n._moments,
            V._moments
        )

        # Check shapes
        if mu_alpha.dims != ( (D,), (D,D), (), () ):
            raise ValueError("mu and alpha have wrong shape")

        if V.dims != ( (D,D), () ):
            raise ValueError("Precision matrix has wrong shape")

        if n.dims != ( (), () ):
            raise ValueError("Degrees of freedom has wrong shape")

        parents = [mu_alpha, n, V]

        return (parents,
                kwargs,
                moments.dims,
                cls._total_plates(kwargs.get('plates'),
                                  cls._distribution.plates_from_parent(0, mu_alpha.plates),
                                  cls._distribution.plates_from_parent(1, n.plates),
                                  cls._distribution.plates_from_parent(2, V.plates)),
                cls._distribution,
                moments,
                parent_moments)

```

I got errors regarding the method _ensure_moments:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/bayespy/inference/vmp/nodes/node.py", line 352, in _ensure_moments
    converter = node._moments.get_converter(moments_class)
AttributeError: 'int' object has no attribute '_moments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../python/main2.py", line 156, in <module>
    app.run(app.parse_arguments())
  File "../python/main2.py", line 123, in run
    e.fit(X_train, y_train)
  File "/home/raphael/Documents/Master Degree/Master Project/Implementation/LazyNN_RF/python/xsklearn/ensemble/stacking.py", line 331, in fit
    lm = nodes.GaussianWishart(mu, 1, D, Lambda)
  File "/usr/local/lib/python3.4/dist-packages/bayespy/inference/vmp/nodes/expfamily.py", line 79, in constructor_decorator
    self._constructor(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/bayespy/inference/vmp/nodes/gaussian.py", line 2045, in _constructor
    n = cls._ensure_moments(n, WishartPriorMoments)
  File "/usr/local/lib/python3.4/dist-packages/bayespy/inference/vmp/nodes/node.py", line 356, in _ensure_moments
    moments_class.from_values(node, **kwargs),
TypeError: from_values() missing 1 required positional argument: 'd'

```
Problems I am facing:
1 - I don't know If I solved the first error by modifing the code like I did
2 - After modifing, I got errors related with _ensure_moments, so how can I properly use GaussianWishart in order to approximate a multivariate Gaussian distribution?

**Comment by jluttine** [comment]
Just a quick reply, I'm not able to try any code at the moment. So, just a quick guess, perhaps something like this would work:
```python
N, D = L.shape
mu_Lambda = nodes.GaussianWishart(
    np.zeros(D),
    1,
    D,
    np.identity(D)
)
x = nodes.Gaussian(mu_Lambda, 1, plates=(N,))
x.observe(L)

Q = VB(x, mu_Lambda)
```
I suppose you want to combine `mu` and `Lambda` into a single node `q(mu, Lambda)`. Also, perhaps you might want to use less informative prior for `mu`, for instance:
```python
mu_Lambda = nodes.GaussianWishart(
    np.zeros(D),
    1e-6,
    D,
    np.identity(D)
)
```

I hope that works. If it doesn't, I'll take another look tomorrow.

**Comment by raphaelcampos** [comment]
Thanks for the rapid response!

I tried the code above, but I am still having the following error:

```
File "/usr/local/lib/python3.4/dist-packages/bayespy/inference/vmp/nodes/expfamily.py", line 79, in constructor_decorator
    self._constructor(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/bayespy/inference/vmp/nodes/gaussian.py", line 2041, in _constructor
    moments = GaussianWishartMoments(shape)
NameError: name 'shape' is not defined
```

**Comment by jluttine** [comment]
Ok, I'll fix that tomorrow (I hope so). Thanks for the report!

**Comment by jluttine** [comment]
Sorry for the delay. I looked into this now. There were a few minor errors that I fixed locally. However, in the end it turned out I haven't yet implemented GaussianWishart distribution. I just have the skeleton with NotImplementedErrors in each method.. I've thought I had it implemented so I'm a bit confused. Well, it isn't so sorry for that. I'll try to implement the methods in the coming days/weeks. `GaussianGamma` is implemented and I've used that myself, so that might be useful if you don't need to learn the full covariance matrix.

**Comment by raphaelcampos** [comment]
That's allright.

Unfortunately, I need to learn the full covariance matrix. However, the usage of Gaussian and Wishart distribution separately is working fine so far. I can wait until you finish to implement GaussianWishart distibution. I am not in a hurry.

Thanks once again.
