### ISSUE TITLE
 contour of GaussianMixture

### ISSUE THREAD

**Issue by nemuo** [bayespy/bayespy#91]
I tried to run the following script of bayespy.

```
x1 = Gaussian([3,5],[[4,2],[2,5]]);
x2 = Gaussian([1,2],[[4,2],[2,5]]);
x3 = Gaussian([2,4],[[4,2],[2,5]]);
z = Add(x1,x2,x3);
bpplt.contour(z, np.linspace(1,5, num=100),np.linspace(3,7, num=100));
bpplt.pyplot.show();
```

Then I've got the following error.

```
Traceback (most recent call last):
  File "C:\home\bin\python3_32\lib\site-packages\bayespy-0.5.6-py3.5.egg\bayespy\plot.py", line 238, in contour
    lpdf = Z.logpdf(XY)
AttributeError: 'Add' object has no attribute 'logpdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bayespytest.py", line 186, in <module>
    bpplt.contour(z, np.linspace(1,5, num=100),np.linspace(3,7, num=100));
  File "C:\home\bin\python3_32\lib\site-packages\bayespy-0.5.6-py3.5.egg\bayespy\plot.py", line 240, in contour
    lpdf = Z(XY)
TypeError: 'Add' object is not callable

```
I tried another approach as follows, but it also fails.

```
x1 = Gaussian([3,5],[[4,2],[2,5]]);
x2 = Gaussian([1,2],[[4,2],[2,5]]);
x3 = Gaussian([2,4],[[4,2],[2,5]]);
w = Dirichlet([1]*3);
z = MultiMixture([x1,x2,x3], Gaussian, w);
bpplt.contour(z, np.linspace(1,5, num=100),np.linspace(3,7, num=100));

Traceback (most recent call last):
  File "./bayespytest.py", line 196, in <module>
    z = MultiMixture([x1,x2,x3], Gaussian, w);
  File "C:\home\bin\python3_32\lib\site-packages\bayespy-0.5.6-py3.5.egg\bayespy\inference\vmp\nodes\mixture.py", line 561, in MultiMixture
    return Mixture(*args, **kwargs)
  File "C:\home\bin\python3_32\lib\site-packages\bayespy-0.5.6-py3.5.egg\bayespy\inference\vmp\nodes\mixture.py", line 427, in __init__
    **kwargs)
  File "C:\home\bin\python3_32\lib\site-packages\bayespy-0.5.6-py3.5.egg\bayespy\inference\vmp\nodes\expfamily.py", line 79, in constructor_decorator
    self._constructor(*args, **kwargs)
  File "C:\home\bin\python3_32\lib\site-packages\bayespy-0.5.6-py3.5.egg\bayespy\inference\vmp\nodes\mixture.py", line 440, in _constructor
    node_class._constructor(*args)
  File "C:\home\bin\python3_32\lib\site-packages\bayespy-0.5.6-py3.5.egg\bayespy\inference\vmp\nodes\mixture.py", line 440, in _constructor
    node_class._constructor(*args)
  File "C:\home\bin\python3_32\lib\site-packages\bayespy-0.5.6-py3.5.egg\bayespy\inference\vmp\nodes\mixture.py", line 440, in _constructor
    node_class._constructor(*args)
TypeError: _constructor() missing 1 required positional argument: 'Lambda'

```
I would like to mix the three specific Gaussian distributions.
How can I remove the errors?

Also, is there any documentation on MultiMixture?

Thanks.

**Comment by jluttine** [comment]
The first part: logpdf is supported only for random variables, not deterministic operations of random variables, because in general it becomes difficult/intractable to find the logpdf. I could consider if there was some way to circumvent this, at least in some cases, but at the moment you can only plot pdfs of stochastic nodes (e.g., Gaussian) but not deterministic nodes (e.g., Add).

The second part: You can construct mixture distributions with `Mixture` when you have only one mixing variable node. The syntax being `Mixture(categorical_node, node_class, *parameters)`. For instance:
```
X = Concatenate(x1[None],x2[None],x3[None])
Z = Categorical(np.ones(3)/3)
Y = Mixture(Z, Gaussian, X, np.identity(2));
```
(You could avoid using Concatenate if you constructed X as a single node with plates in the first place.) You can plot `Y` as:
```
bpplt.contour(Y, np.linspace(1,5, num=100),np.linspace(3,7, num=100));
```
However, the results might not be what you'd expect: it's just a Gaussian distribution with mean in the mean of x1,x2,x3 and unit variance (the identity matrix I gave to Mixture).
