### ISSUE TITLE
ImageComparisonFailure with matplotilb 2.0

### ISSUE THREAD

**Issue by ghisvail** [bayespy/bayespy#97]
I am using the latest source of `bayespy` available on PyPI. The tests fail with the following error on Debian Stretch:

```
======================================================================
FAIL: bayespy.tests.test_plot.test_gaussian_mixture_plot.test(1, '/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/result_images/test_plot/gaussian_mixture.png', '/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/result_images/test_plot/gaussian_mixture-expected.png')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/decorators.py", line 58, in failer
    result = f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/decorators.py", line 259, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.exceptions.ImageComparisonFailure: images not close: /<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/result_images/test_plot/gaussian_mixture.png vs. /<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/result_images/test_plot/gaussian_mixture-expected.png (RMS 1.400)

----------------------------------------------------------------------
```

**Comment by jluttine** [comment]
Which versions of Python and Matplotlib are you using with BayesPy?

**Comment by ghisvail** [comment]
Python 3.5.3 and Matplotlib 2.0.0

**Comment by ghisvail** [comment]
Any idea where this could come from?

**Comment by ghisvail** [comment]
I get the same issue when running the tests in a `venv`, so the issue does not sound Debian specific:

```
======================================================================
FAIL: bayespy.tests.test_plot.test_contour_plot.test(1, '/home/gvaillan/.virtualenvs/bayespy/src/bayespy/result_images/test_plot/contour.png', '/home/gvaillan/.virtualenvs/bayespy/src/bayespy/result_images/test_plot/contour-expected.png')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gvaillan/.virtualenvs/bayespy/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/gvaillan/.virtualenvs/bayespy/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 58, in failer
    result = f(*args, **kwargs)
  File "/home/gvaillan/.virtualenvs/bayespy/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 249, in do_test
    self._tol, in_decorator=True)
  File "/home/gvaillan/.virtualenvs/bayespy/lib/python3.5/site-packages/matplotlib/testing/compare.py", line 345, in compare_images
    rms = calculate_rms(expectedImage, actualImage)
  File "/home/gvaillan/.virtualenvs/bayespy/lib/python3.5/site-packages/matplotlib/testing/compare.py", line 256, in calculate_rms
    "actual size {1}".format(expectedImage.shape, actualImage.shape))
matplotlib.testing.exceptions.ImageComparisonFailure: image sizes do not match expected size: (600, 800, 3) actual size (480, 640, 3)


======================================================================
FAIL: bayespy.tests.test_plot.test_gaussian_mixture_plot.test(1, '/home/gvaillan/.virtualenvs/bayespy/src/bayespy/result_images/test_plot/gaussian_mixture.png', '/home/gvaillan/.virtualenvs/bayespy/src/bayespy/result_images/test_plot/gaussian_mixture-expected.png')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gvaillan/.virtualenvs/bayespy/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/gvaillan/.virtualenvs/bayespy/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 58, in failer
    result = f(*args, **kwargs)
  File "/home/gvaillan/.virtualenvs/bayespy/lib/python3.5/site-packages/matplotlib/testing/decorators.py", line 259, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.exceptions.ImageComparisonFailure: images not close: /home/gvaillan/.virtualenvs/bayespy/src/bayespy/result_images/test_plot/gaussian_mixture.png vs. /home/gvaillan/.virtualenvs/bayespy/src/bayespy/result_images/test_plot/gaussian_mixture-expected.png (RMS 1.400)


----------------------------------------------------------------------
Ran 141 tests in 11.606s

FAILED (failures=2)
```

**Comment by jluttine** [comment]
Sorry, I haven't had time to look at it yet. Most likely it's nothing to be worried about. I guess Matplotlib 2.0 has changed the default plotting styles a bit (or more than a bit) and this causes image difference when comparing to an image generated with an older version of Matplotlib.

You can open the two images (the error message shows the paths on the last line) and compare them visually. If you upload your result image `/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/result_images/test_plot/gaussian_mixture.png` here, I can take a look.

But as I said, I believe this is most likely related to matplotlib 2.0 changes and only some minor visual changes. But I haven't taken a closer look yet.

**Comment by jluttine** [comment]
If you want, you can downgrade matplotlib<2.0 and see if you still get the error.

**Comment by ghisvail** [comment]
I cannot downgrade Debian packages as I can easily do on a `venv` unfortunately. The `venv` test was just to confirm the issue was not specific to the Debian packaged dependencies. So, I am definitely interested in a fix for `matplotlib>=2.0`. I'll upload the images you requested.

**Comment by ghisvail** [comment]
![contour](https://cloud.githubusercontent.com/assets/1964655/23897490/4b9c81f0-08a5-11e7-8934-735c3ce8adfa.png)
![contour-expected](https://cloud.githubusercontent.com/assets/1964655/23897489/4b9c0fc2-08a5-11e7-952a-72a40dd6c96c.png)
![gaussian_mixture](https://cloud.githubusercontent.com/assets/1964655/23897488/4b9c1e18-08a5-11e7-9d96-7526e6c2d81e.png)
![gaussian_mixture-expected](https://cloud.githubusercontent.com/assets/1964655/23897491/4b9e6416-08a5-11e7-9e45-8a9048c1e299.png)

**Comment by jluttine** [comment]
Thanks! In the first one, I can see that the plot size has slightly increased. In the latter comparison, I don't see any difference visually, I would have to make an image diff comparison with some app.

Anyway, you can ignore these test errors. These errors aren't related to any functionality. Yes, they need to be fixed, but everything is working ok.

**Comment by ghisvail** [comment]
May I suggest to use this opportunity to replace the use of `nose` with `pytest`. The former is unmaintained and the latter would allow for easy discard of the failing tests.

**Comment by jluttine** [comment]
Yes, you may. Actually, it's been on my todo-list for some time to replace nose with pytest. I've done it already some other projects. It requires a bit of work in BayesPy as it's integrated to doctests etc. But anyway, it should be done. I opened a new issue for it: https://github.com/bayespy/bayespy/issues/98

**Comment by ghisvail** [comment]
For now, I am using `node-exclude` to explicitly disable the offending tests without patching the code base. It'd be nice however if the full test suite were working again at some point.

**Comment by jluttine** [comment]
Thanks for reminding. Yes, this needs to be fixed. I try to take a look soon.

**Comment by jluttine** [comment]
This is probably now fixed in develop. I'll make a new release some day.

**Comment by ghisvail** [comment]
Still getting this:
```
======================================================================
FAIL: bayespy.tests.test_plot.test_contour_plot.test(1, '/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.6/build/result_images/test_plot/contour.png', '/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.6/build/result_images/test_plot/contour-expected.png')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/decorators.py", line 58, in failer
    result = f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/decorators.py", line 249, in do_test
    self._tol, in_decorator=True)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/compare.py", line 345, in compare_images
    rms = calculate_rms(expectedImage, actualImage)
  File "/usr/lib/python3/dist-packages/matplotlib/testing/compare.py", line 256, in calculate_rms
    "actual size {1}".format(expectedImage.shape, actualImage.shape))
matplotlib.testing.exceptions.ImageComparisonFailure: image sizes do not match expected size: (480, 640, 3) actual size (600, 800, 3)
```

**Comment by jluttine** [comment]
Thanks for reporting. These are really annoying test errors because small changes in matplotlib versions or the system might cause differences in the images. Probably, I'll just discard image comparison tests..

**Comment by jluttine** [comment]
New release 0.5.11 should fix this issue by skipping the test.
